/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon { 'code' : string, 'discount' : bigint }
export interface Dish {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : string,
  'category' : string,
  'isVeg' : boolean,
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'user' : Principal,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<[string, bigint, bigint]>,
}
export interface Reservation {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'time' : string,
  'user' : Principal,
  'timestamp' : Time,
  'phone' : string,
  'guests' : bigint,
}
export interface Review {
  'user' : Principal,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'address' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoupon' : ActorMethod<[string, bigint], undefined>,
  'addDish' : ActorMethod<
    [string, string, bigint, string, string, boolean, boolean],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDish' : ActorMethod<[bigint], undefined>,
  'editDish' : ActorMethod<
    [bigint, string, string, bigint, string, string, boolean, boolean],
    undefined
  >,
  'generateMenuCode' : ActorMethod<[], string>,
  'getAllDishes' : ActorMethod<[], Array<Dish>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDishesByCategory' : ActorMethod<[string], Array<Dish>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReservations' : ActorMethod<[Principal], Array<Reservation>>,
  'getVegDishes' : ActorMethod<[], Array<Dish>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'makeReservation' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'placeOrder' : ActorMethod<
    [Array<[string, bigint, bigint]>, bigint, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'submitReview' : ActorMethod<[bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'verifyMenuCode' : ActorMethod<[string, string], [boolean, string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];